# Generated by Django 2.1.2 on 2019-01-02 07:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
                ('release', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('video', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('view', models.IntegerField()),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 1, 2, 7, 59, 55, 678053))),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 1, 2, 7, 59, 55, 678073))),
            ],
        ),
        migrations.CreateModel(
            name='producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('id_posts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.posts')),
            ],
        ),
        migrations.CreateModel(
            name='writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('id_posts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.posts')),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='id_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.posts'),
        ),
        migrations.AddField(
            model_name='details',
            name='id_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.posts'),
        ),
        migrations.AddField(
            model_name='additional',
            name='id_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.posts'),
        ),
        migrations.AddField(
            model_name='actor',
            name='id_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.posts'),
        ),
    ]
