# Generated by Django 2.1.2 on 2019-01-02 07:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='keywords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('view', models.IntegerField()),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 1, 2, 7, 59, 55, 677162))),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 1, 2, 7, 59, 55, 677183))),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('version', models.CharField(max_length=25)),
                ('view', models.IntegerField()),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 1, 2, 7, 59, 55, 675303))),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 1, 2, 7, 59, 55, 675333))),
            ],
        ),
        migrations.CreateModel(
            name='screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('id_posts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.posts')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('id_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.Categories')),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='id_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.posts'),
        ),
        migrations.AddField(
            model_name='additional',
            name='id_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.posts'),
        ),
    ]
